### PR TITLE
Add clang format

### PR DESCRIPTION
**Pull request by Ughuuu**
The idea is to have a lint job that runs before all builds jobs.
Also, have double builds. Also, upload everything to same artifact so it can be downloaded from individual jobs.

TODO
For mac signing we need a folder(framework) that contains the dylib. Also a resource near it. For this we need the build folder to exist beforehand in source or to copy it from somewhere.

Also, I want to export the gdextension also with the build. I only found gdextension inside sample/extensions/..

This path is also kinda wrong. Extensions in godot are called addons. So the path should be sample/addons/..

But here too, the path used when uploading a package is kept, so if I upload a package, it will be sample/extensions.. So later if I want to download it and have it just work. Anyway, I can also do a rename, but I would prefer not to, so there is no magic involved.

### CODE REVIEW

**Review by fire — APPROVED** [review]
I like the proposal, but it's still failing cicd, but feel free to merge when it passes.

**Comment by Ughuuu** [comment]
Its close, need to make macos pass. Checking the whole universal thingy. Might do signing in a later pr.

**Comment by RechieKho** [comment]
If You mean creating Universal build, I wonder how will it affect development experience?

As you set the GDExtension configuration file to link to universal library, then wouldn't that us Mac os user would need to compile universal build as well? Cross compiling iree is not easy...

Unless there is a way to link to native library when development and link to universal one on CI/CD.

**Comment by RechieKho** [comment]
If You mean creating Universal build, I wonder how will it affect development experience?

As you set the GDExtension configuration file to link to universal library, then wouldn't that us Mac os user would need to compile universal build as well? Cross compiling iree is not easy...

Unless there is a way to link to native library when development and link to universal one on CI/CD.

**Comment by Ughuuu** [comment]
There is a way to link universal one in gdextension.
Also, I think you can just link the arm64 one as well and not use the universal one for development.

**Review by RechieKho — APPROVED** [review]

**Comment by Ughuuu** [comment]
I'll investigate some more the singing, opened a ticket(for now you have to go to settings and approve it) with apple about it with code level support, see where I get. For now I'll merge this PR as it adds a lot of things.

**Pull request merged**
